import type {
  Stage,
  Transaction,
  Task,
  ChecklistItem,
  DocumentItem,
  Contact,
  TimelineEvent,
  SmartPlanEnrollment,
  SmartPlanTemplate,
} from "./types"

export const stages: Stage[] = [
  { key: "lead", label: "Lead mới" },
  { key: "consulting", label: "Tư vấn" },
  { key: "viewing", label: "Xem nhà" },
  { key: "deposit", label: "Đặt cọc" },
  { key: "docs", label: "Hồ sơ" },
  { key: "notary", label: "Công chứng" },
  { key: "transfer", label: "Sang tên" },
  { key: "handover", label: "Bàn giao" },
  { key: "aftercare", label: "Hậu mãi" },
]

const today = new Date().toISOString().split("T")[0]
const yesterday = new Date(Date.now() - 86400000).toISOString().split("T")[0]
const twoDaysAgo = new Date(Date.now() - 172800000).toISOString().split("T")[0]

export const initialTransactions: Transaction[] = [
  {
    id: "tx-001",
    title: "Bán căn hộ Vinhomes Grand Park S5.03",
    customerName: "Nguyễn Văn An",
    phone: "0901234567",
    propertyLabel: "Vinhomes Grand Park S5.03.12",
    stage: "lead",
    value: 3200000000,
    createdAt: "2026-02-10",
    updatedAt: today,
    missingDocsCount: 0,
    overdueTasksCount: 0,
  },
  {
    id: "tx-002",
    title: "Cho thuê văn phòng Quận 1",
    customerName: "Trần Thị Bình",
    phone: "0912345678",
    propertyLabel: "Tòa nhà AB Tower, Q1",
    stage: "consulting",
    value: 450000000,
    createdAt: "2026-02-08",
    updatedAt: today,
    missingDocsCount: 0,
    overdueTasksCount: 1,
  },
  {
    id: "tx-003",
    title: "Mua đất nền Long An",
    customerName: "Lê Hoàng Cường",
    phone: "0923456789",
    propertyLabel: "KDC Tân Đức, Long An",
    stage: "viewing",
    value: 1800000000,
    createdAt: "2026-02-05",
    updatedAt: yesterday,
    missingDocsCount: 0,
    overdueTasksCount: 0,
  },
  {
    id: "tx-004",
    title: "Bán biệt thự Thảo Điền",
    customerName: "Phạm Minh Đức",
    phone: "0934567890",
    propertyLabel: "Biệt thự 123 Nguyễn Văn Hưởng",
    stage: "deposit",
    value: 25000000000,
    createdAt: "2026-01-20",
    updatedAt: yesterday,
    missingDocsCount: 2,
    overdueTasksCount: 1,
  },
  {
    id: "tx-005",
    title: "Bán căn hộ Masteri Thảo Điền",
    customerName: "Võ Thị Em",
    phone: "0945678901",
    propertyLabel: "Masteri T3.15.08",
    stage: "docs",
    value: 5500000000,
    createdAt: "2026-01-15",
    updatedAt: twoDaysAgo,
    missingDocsCount: 3,
    overdueTasksCount: 2,
  },
  {
    id: "tx-006",
    title: "Cho thuê shophouse Phú Mỹ Hưng",
    customerName: "Hoàng Gia Phúc",
    phone: "0956789012",
    propertyLabel: "Shophouse PMH, Q7",
    stage: "notary",
    value: 800000000,
    createdAt: "2026-01-10",
    updatedAt: twoDaysAgo,
    missingDocsCount: 0,
    overdueTasksCount: 0,
  },
  {
    id: "tx-007",
    title: "Bán căn hộ The Sun Avenue",
    customerName: "Đỗ Thanh Giang",
    phone: "0967890123",
    propertyLabel: "Sun Avenue S2.10.05",
    stage: "transfer",
    value: 4100000000,
    createdAt: "2026-01-05",
    updatedAt: yesterday,
    missingDocsCount: 1,
    overdueTasksCount: 0,
  },
  {
    id: "tx-008",
    title: "Bán nhà phố Quận 2",
    customerName: "Bùi Văn Hải",
    phone: "0978901234",
    propertyLabel: "Nhà 45 Thảo Điền, Q2",
    stage: "handover",
    value: 12000000000,
    createdAt: "2025-12-20",
    updatedAt: today,
    missingDocsCount: 0,
    overdueTasksCount: 0,
  },
  {
    id: "tx-009",
    title: "Cho thuê căn hộ Gateway",
    customerName: "Mai Thị Inh",
    propertyLabel: "Gateway Thảo Điền T2.08",
    stage: "aftercare",
    value: 180000000,
    createdAt: "2025-12-15",
    updatedAt: twoDaysAgo,
    missingDocsCount: 0,
    overdueTasksCount: 0,
  },
  {
    id: "tx-010",
    title: "Bán căn hộ Saigon Pearl",
    customerName: "Nguyễn Thị Kim",
    phone: "0989012345",
    propertyLabel: "Saigon Pearl Ruby 1.20.03",
    stage: "lead",
    value: 6800000000,
    createdAt: "2026-02-20",
    updatedAt: today,
    missingDocsCount: 0,
    overdueTasksCount: 0,
  },
  {
    id: "tx-011",
    title: "Mua đất Nhơn Trạch",
    customerName: "Trần Văn Long",
    phone: "0990123456",
    propertyLabel: "Lô A5-12 KDC Nhơn Trạch",
    stage: "consulting",
    value: 2100000000,
    createdAt: "2026-02-12",
    updatedAt: yesterday,
    missingDocsCount: 1,
    overdueTasksCount: 0,
  },
  {
    id: "tx-012",
    title: "Cho thuê villa Đà Lạt",
    customerName: "Phan Thị Mai",
    phone: "0901122334",
    propertyLabel: "Villa Đồi Thông, Đà Lạt",
    stage: "viewing",
    value: 360000000,
    createdAt: "2026-02-18",
    updatedAt: today,
    missingDocsCount: 0,
    overdueTasksCount: 1,
  },
]

export const initialTasks: Task[] = [
  {
    id: "task-001",
    transactionId: "tx-001",
    title: "Gọi điện xác nhận lịch xem nhà",
    dueAt: today,
    status: "open",
    assigneeName: "Minh Tú",
  },
  {
    id: "task-002",
    transactionId: "tx-002",
    title: "Gửi bảng giá cho khách",
    dueAt: today,
    status: "open",
    assigneeName: "Minh Tú",
  },
  {
    id: "task-003",
    transactionId: "tx-004",
    title: "Thu thập giấy tờ đặt cọc",
    dueAt: yesterday,
    status: "open",
    assigneeName: "Minh Tú",
  },
  {
    id: "task-004",
    transactionId: "tx-005",
    title: "Kiểm tra hồ sơ pháp lý",
    dueAt: yesterday,
    status: "open",
    assigneeName: "Minh Tú",
  },
  {
    id: "task-005",
    transactionId: "tx-005",
    title: "Liên hệ ngân hàng về khoản vay",
    dueAt: twoDaysAgo,
    status: "open",
    assigneeName: "Minh Tú",
  },
  {
    id: "task-006",
    transactionId: "tx-003",
    title: "Chuẩn bị tài liệu xem đất",
    dueAt: today,
    status: "done",
    assigneeName: "Minh Tú",
  },
  {
    id: "task-007",
    transactionId: "tx-007",
    title: "Nộp hồ sơ sang tên",
    dueAt: today,
    status: "open",
    assigneeName: "Minh Tú",
  },
  {
    id: "task-008",
    transactionId: "tx-008",
    title: "Kiểm tra tình trạng bàn giao",
    dueAt: today,
    status: "open",
    assigneeName: "Minh Tú",
  },
  {
    id: "task-009",
    transactionId: "tx-012",
    title: "Xác nhận lịch xem villa",
    dueAt: today,
    status: "open",
    assigneeName: "Minh Tú",
  },
  {
    id: "task-010",
    transactionId: "tx-010",
    title: "Gửi thông tin dự án cho khách",
    dueAt: today,
    status: "open",
    assigneeName: "Minh Tú",
  },
]

export const initialChecklistItems: ChecklistItem[] = [
  { id: "cl-001", transactionId: "tx-004", title: "CMND/CCCD người mua", status: "done" },
  { id: "cl-002", transactionId: "tx-004", title: "Hợp đồng đặt cọc", status: "done" },
  { id: "cl-003", transactionId: "tx-004", title: "Biên nhận tiền cọc", status: "todo", dueAt: today },
  { id: "cl-004", transactionId: "tx-004", title: "Sổ đỏ bản gốc", status: "todo", dueAt: yesterday },
  { id: "cl-005", transactionId: "tx-005", title: "CMND/CCCD người bán", status: "done" },
  { id: "cl-006", transactionId: "tx-005", title: "Sổ đỏ bản sao", status: "todo" },
  { id: "cl-007", transactionId: "tx-005", title: "Giấy xác nhận tình trạng hôn nhân", status: "todo" },
  { id: "cl-008", transactionId: "tx-005", title: "Hợp đồng mua bán (draft)", status: "todo", dueAt: today },
  { id: "cl-009", transactionId: "tx-007", title: "Biên bản bàn giao", status: "done" },
  { id: "cl-010", transactionId: "tx-007", title: "Hóa đơn thanh toán", status: "todo", dueAt: today },
  { id: "cl-011", transactionId: "tx-008", title: "Biên bản nghiệm thu", status: "done" },
  { id: "cl-012", transactionId: "tx-008", title: "Chìa khóa + thẻ ra vào", status: "done" },
]

export const initialDocuments: DocumentItem[] = [
  { id: "doc-001", transactionId: "tx-004", name: "CMND Phạm Minh Đức", type: "id_docs", uploadedAt: "2026-01-21" },
  { id: "doc-002", transactionId: "tx-004", name: "Hợp đồng đặt cọc v1", type: "contract", uploadedAt: "2026-01-22" },
  { id: "doc-003", transactionId: "tx-005", name: "CCCD Võ Thị Em", type: "id_docs", uploadedAt: "2026-01-16" },
  { id: "doc-004", transactionId: "tx-005", name: "Sổ đỏ scan", type: "red_book", uploadedAt: "2026-01-17" },
  { id: "doc-005", transactionId: "tx-006", name: "Hợp đồng thuê", type: "contract", uploadedAt: "2026-01-11" },
  { id: "doc-006", transactionId: "tx-007", name: "Biên nhận cọc", type: "deposit_receipt", uploadedAt: "2026-01-06" },
  { id: "doc-007", transactionId: "tx-007", name: "Hợp đồng mua bán", type: "contract", uploadedAt: "2026-01-07" },
  { id: "doc-008", transactionId: "tx-008", name: "Biên bản bàn giao", type: "misc", uploadedAt: "2025-12-21" },
  { id: "doc-009", transactionId: "tx-011", name: "Giấy phép quy hoạch", type: "misc", uploadedAt: "2026-02-13" },
]

export const initialContacts: Contact[] = [
  { id: "ct-001", name: "Nguyễn Văn An", role: "buyer", phone: "0901234567", budget: 3500000000, area: "TP Thủ Đức", lastActivityAt: today },
  { id: "ct-002", name: "Trần Thị Bình", role: "tenant", phone: "0912345678", budget: 50000000, area: "Quận 1", lastActivityAt: today },
  { id: "ct-003", name: "Lê Hoàng Cường", role: "buyer", phone: "0923456789", budget: 2000000000, area: "Long An", lastActivityAt: yesterday },
  { id: "ct-004", name: "Phạm Minh Đức", role: "buyer", phone: "0934567890", budget: 30000000000, area: "Quận 2", lastActivityAt: yesterday },
  { id: "ct-005", name: "Võ Thị Em", role: "seller", phone: "0945678901", area: "Quận 2", lastActivityAt: twoDaysAgo },
  { id: "ct-006", name: "Hoàng Gia Phúc", role: "tenant", phone: "0956789012", budget: 100000000, area: "Quận 7", lastActivityAt: twoDaysAgo },
  { id: "ct-007", name: "Đỗ Thanh Giang", role: "seller", phone: "0967890123", area: "Quận 2", lastActivityAt: yesterday },
  { id: "ct-008", name: "Bùi Văn Hải", role: "buyer", phone: "0978901234", budget: 15000000000, area: "Quận 2", lastActivityAt: today },
  { id: "ct-009", name: "Mai Thị Inh", role: "landlord", phone: "0989012345", area: "Quận 2", lastActivityAt: twoDaysAgo },
  { id: "ct-010", name: "Nguyễn Thị Kim", role: "buyer", phone: "0990123456", budget: 7000000000, area: "Bình Thạnh", lastActivityAt: today },
  { id: "ct-011", name: "Trần Văn Long", role: "buyer", phone: "0901122334", budget: 2500000000, area: "Nhơn Trạch", lastActivityAt: yesterday },
  { id: "ct-012", name: "Phan Thị Mai", role: "landlord", phone: "0912233445", area: "Đà Lạt", lastActivityAt: today },
  { id: "ct-013", name: "Lý Văn Nam", role: "seller", phone: "0923344556", area: "Quận 9", lastActivityAt: "2026-02-15" },
  { id: "ct-014", name: "Đinh Thị Oanh", role: "buyer", phone: "0934455667", budget: 5000000000, area: "Quận 7", lastActivityAt: "2026-02-14" },
  { id: "ct-015", name: "Cao Minh Phát", role: "tenant", phone: "0945566778", budget: 30000000, area: "Quận 3", lastActivityAt: "2026-02-13" },
]

export const initialTimelineEvents: TimelineEvent[] = [
  { id: "ev-001", transactionId: "tx-004", action: "Tạo giao dịch mới", timestamp: "2026-01-20T09:00:00Z", actor: "Minh Tú" },
  { id: "ev-002", transactionId: "tx-004", action: "Chuyển sang giai đoạn Đặt cọc", timestamp: "2026-01-22T14:30:00Z", actor: "Minh Tú" },
  { id: "ev-003", transactionId: "tx-004", action: "Tải lên CMND khách hàng", timestamp: "2026-01-21T10:00:00Z", actor: "Minh Tú" },
  { id: "ev-004", transactionId: "tx-005", action: "Tạo giao dịch mới", timestamp: "2026-01-15T08:00:00Z", actor: "Minh Tú" },
  { id: "ev-005", transactionId: "tx-005", action: "Chuyển sang giai đoạn Hồ sơ", timestamp: "2026-01-18T11:00:00Z", actor: "Minh Tú" },
  { id: "ev-006", transactionId: "tx-008", action: "Bàn giao nhà thành công", timestamp: "2026-02-25T09:00:00Z", actor: "Minh Tú" },
  { id: "ev-007", transactionId: "tx-001", action: "Tạo giao dịch mới", timestamp: "2026-02-10T10:00:00Z", actor: "Minh Tú" },
  { id: "ev-008", transactionId: "tx-007", action: "Nộp hồ sơ sang tên", timestamp: "2026-02-20T15:00:00Z", actor: "Minh Tú" },
]

export const smartPlanEnrollments: SmartPlanEnrollment[] = [
  { id: "sp-001", transactionId: "tx-004", templateName: "Quy trình đặt cọc", status: "active", nextActionAt: today, nextAction: "Nhắc thu giấy tờ còn thiếu" },
  { id: "sp-002", transactionId: "tx-005", templateName: "Quy trình hồ sơ", status: "active", nextActionAt: today, nextAction: "Kiểm tra hồ sơ pháp lý" },
  { id: "sp-003", transactionId: "tx-007", templateName: "Quy trình sang tên", status: "active", nextActionAt: yesterday, nextAction: "Xác nhận hoàn tất sang tên" },
  { id: "sp-004", transactionId: "tx-009", templateName: "Quy trình hậu mãi", status: "completed", nextActionAt: twoDaysAgo, nextAction: "Hoàn tất" },
]

export const smartPlanTemplates: SmartPlanTemplate[] = [
  { id: "tpl-001", name: "Quy trình đặt cọc", description: "Tự động tạo checklist và nhắc việc khi chuyển sang giai đoạn đặt cọc", triggerStage: "deposit", actionsCount: 5 },
  { id: "tpl-002", name: "Quy trình hồ sơ", description: "Kiểm tra đầy đủ giấy tờ và pháp lý", triggerStage: "docs", actionsCount: 8 },
  { id: "tpl-003", name: "Quy trình công chứng", description: "Chuẩn bị hồ sơ công chứng và đặt lịch", triggerStage: "notary", actionsCount: 4 },
  { id: "tpl-004", name: "Quy trình sang tên", description: "Theo dõi quá trình sang tên sổ đỏ", triggerStage: "transfer", actionsCount: 6 },
  { id: "tpl-005", name: "Quy trình hậu mãi", description: "Chăm sóc khách hàng sau giao dịch", triggerStage: "aftercare", actionsCount: 3 },
]
